defaults: &defaults
  docker:
    - image: circleci/python:3.6

version: 2
jobs:
  # Testing job which builds a small model and runs sanity tests
  # against it.
  test-gen:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user tox
      - run: python -m tox
      - persist_to_workspace:
          root: generate
          paths:
            - assets
            - data/*

  # Job that creates a tar archive for the python library.
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: 'model'
      - run: mkdir target_finder_model/data
      - run: mv model/weights/yolo3detector-train_final.weights target_finder_model/data/yolo3detector-train_final.weights
      - run: mv model/weights/preclf-train_final.weights target_finder_model/data/preclf-train_final.weights
      - run: cp model/cfgs/preclf-test.cfg target_finder_model/data/preclf-test.cfg
      - run: cp model/cfgs/yolo3detector-test.cfg target_finder_model/data/yolo3detector-test.cfg
      - run: ./scripts/create-release.sh
      - store_artifacts:
          path: release
          destination: release
      - persist_to_workspace:
          root: '.'
          paths:
            - release

workflows:
  version: 2
  test-generate-train:
    jobs:
      - test-gen
