defaults: &defaults
  docker:
    - image: circleci/python:3.6

version: 2
jobs:
  # Testing job which builds a small model and runs sanity tests
  # against it.
  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user tox
      - run: python -m tox
      - persist_to_workspace:
          root: generate
          paths:
            - assets
      - run: tar -cvzf test-data.tar.gz generate/data
      - store_artifacts:
          path: test-data.tar.gz
          destination: test-data.tar.gz

  # Parallel jobs to build shapes.
  part-a-gen: &image-gen-job
    <<: *defaults
    environment:
      - NUM_OFFSET: 0
      - NUM_IMAGES: 10
      - NUM_VAL_OFFSET: 0
      - NUM_VAL_IMAGES: 10
    steps:
      - checkout
      - attach_workspace:
          at: generate
      - run: pip install --user -r requirements-dev.txt
      - run: python generate/create_full_images.py
      - run: python generate/create_clf_data.py
      - run: python generate/create_detection_data.py
      - persist_to_workspace:
          root: generate
          paths:
            - data/*
  part-b-gen:
    <<: *image-gen-job
    environment:
      - NUM_OFFSET: 10
      - NUM_IMAGES: 10
      - NUM_VAL_OFFSET: 10
      - NUM_VAL_IMAGES: 10

  setup-darknet:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target_finder_model
      - run: pip install --user -r requirements-dev.txt
      - run: git clone https://github.com/AlexeyAB/darknet.git
      - run: make -C ./darknet
      - persist_to_workspace:
          root: darknet
          paths:
            - *

  # Training job using the shapes from the shapes above.
  train: &image-train-job
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target_finder_model
      - run: source scripts/train-detector.sh
      - persist_to_workspace:
          root: model
          paths:
            - weights/*
  train-clf:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target_finder_model
      - run: source scripts/train-preclf.sh
      - persist_to_workspace:
          root: model
          paths:
            - weights/*

  # Job that creates a tar archive for the python library.
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: target_finder_model
      - run: ./scripts/create-release.sh
      - store_artifacts:
          path: release
          destination: release
      - persist_to_workspace:
          root: '.'
          paths:
            - release

  # Job that publishes to GitHub Releases for tags.
  publish:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: '.'
      - run: |
          ghr \
            -t ${GITHUB_TOKEN} \
            -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME} \
            -c ${CIRCLE_SHA1} \
            -delete \
            ${CIRCLE_TAG} \
            ./release/

workflows:
  version: 2
  test-generate-train:
    jobs:
      - test
      - setup-darknet
      - part-a-gen: &gen-job
          requires:
            - test
      - part-b-gen:
          <<: *gen-job
      - train: &train-job
          requires:
            - part-a-gen
            - part-b-gen
            - setup-darknet
      - train-clf:
          <<: *train-job
      - release:
          requires:
            - train
            - train-clf
