FROM nvcr.io/nvidia/tensorflow:19.10-py3
 
WORKDIR /sources

RUN apt-get update \
    && apt-get install -y \
	git \
        protobuf-compiler \ 
    && rm -rf /var/lib/apt/lists/*

COPY requirements-docker.txt .

RUN apt install python3-pip \
  && pip3 install --upgrade pip 

RUN pip3 install -r requirements-docker.txt \
  && pip3 install --upgrade tf-nightly


WORKDIR /host
