name: create-release

on: 
  # Only trigger release creation on 
  # push to master.
  push:
    branches:
      - tfrt-update

jobs:
  build:
    name: Build Package and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 3

      - name: Create release tar
        run: ./scripts/create-release.sh
        
      - name: Remove everything except the package
        run: |
          mv release/*.tar.gz .
          find . -type f  ! -name "*.tar.gz*" -delete
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v1.0.0
          release_name: v1.0.0
          draft: false
          prerelease: true
