name: Target Finder Model

on: ["push", "pull_request"]

jobs:

  build-env:
    runs-on: ubuntu-latest

    steps:

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make tf1

    - name: Push target-finder-model-env
      run: docker push uavaustin/target-finder-model-env:tf1

  test: 

    needs: build-env
    runs-on: ubuntu-latest
    name: Generate Data and TF-Records

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build target-finder-model-env:test and test code
      working-directory: ./Dockerfiles
      run: make test

    - name: Upload generated tf-records
      uses: actions/upload-artifact@master
      with:
        name: tf-records
        path: model_data/records

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        parallel: true
        path-to-lcov: .coverage 

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        parallel-finished: true
