name: build

on: ["push", "pull_request"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make tf1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install tox 
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: tox

    - name: Push target-finder-model-env
      run: docker push uavaustin/target-finder-model-env:tf1

    - name: Send slack notification.
      uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        text: Build and test.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
  build-tf2-image:
    runs-on: ubuntu-latest
    steps:

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make tf2

    - name: Push target-finder-model-env
      run: docker push uavaustin/target-finder-model-env:tf2