name: Target Finder Model

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make image

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: ./
    - name: run action.yml
        id: tox
        uses: uavaustin/target-finder-model/action@v1
        with:
          tox-test: tox

