name: build

on: ["push", "pull_request"]

jobs:

  build-tf1-image:
    runs-on: ubuntu-latest
    steps:

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make tf1

    - name: Push target-finder-model-env
      run: docker push uavaustin/target-finder-model-env:tf1
    
  build-tf2-image:
    runs-on: ubuntu-latest
    steps:

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Checkout code 
      uses: actions/checkout@v1

    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make tf2

    - name: Push target-finder-model-env
      run: docker push uavaustin/target-finder-model-env:tf2

  build-data: 
    needs: build-tf1-image
    runs-on: ubuntu-latest
    name: Generate Data and Test
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build target-finder-model-env:test and test code
      working-directory: ./Dockerfiles
      run: make test DOCKERARGS=coveralls

    - name: Upload generated tf-records
      uses: actions/upload-artifact@master
      with:
        name: tf-records
        path: model_data/records
        
  slack-notification:
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        text: overwrite text
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}