name: Target Finder Model

on: [push]

jobs:

  build-env:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make image

  build-test-env:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build target-finder-model-env Docker image
      working-directory: ./Dockerfiles
      run: make test-build

  gen-data:

    runs-on: ubuntu-latest
    name: Run Test Through Entrypoint

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: ./Dockerfiles
    - name: Build Sample Data
      id: build_data
      uses: uavaustin/target-finder-model/Dockerfiles@tfrt-update
      with:
        test: python3 scripts_generate/build.py

  gen-tf-records:

    needs: gen-data
    runs-on: ubuntu-latest
    name: Run Test Through Entrypoint

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: ./Dockerfiles
    - name: Build Sample Data
      id: build_data
      uses: uavaustin/target-finder-model/Dockerfiles@tfrt-update
      with:
        test: python3 scripts_tf/create_tf_records.py --image_dir ./scripts_generate/data --output_dir ./model_data/records

